#!/usr/bin/env python3
"""Generate lint configuration for a world's verb tree.

Verb code is ordinary Python, but the engine injects the verb's context --
`pobj`, `this`, `db`, `call_verb` and ~180 others -- rather than the file
importing it.  A linter that does not know that reports every one as an
undefined name: 26 of them in a single mid-sized verb, all false.

This writes a `ruff.toml` declaring those names as builtins, and a `.pyi`
stub so an editor's language server can complete them.

The list is assembled from the three places the engine builds a namespace
(see moo/verb_namespace.py, moo/verb_types.py) rather than hand-kept, so
regenerating after an engine upgrade is the whole maintenance story.

Usage:
    python tools/gen_verb_lint_config.py [<project-dir>]
"""
import os
import re
import sys
import builtins

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.dirname(HERE)


def _from_namespace_builder():
    """Names assigned as namespace['x'] in verb_namespace.py."""
    src = open(os.path.join(ENGINE, 'moo', 'verb_namespace.py')).read()
    return set(re.findall(r"namespace\['([A-Za-z_]\w*)'\]", src))


def _from_verb_types():
    """Parsed attributes MasterVerb documents and sets on the verb."""
    src = open(os.path.join(ENGINE, 'moo', 'verb_types.py')).read()
    names = set(re.findall(r"^\s*``([a-z_]\w*)``", src, re.M))
    names |= set(re.findall(r"self\.([a-z_]\w*)\s*=", src))
    return names


def _from_moo_builtins():
    """MOO-semantics helpers: moo_eq, moo_ne, moo_in and friends."""
    sys.path.insert(0, ENGINE)
    from moo import moo_builtins as mbi
    return set(getattr(mbi, '__all__', ())) | {
        n for n in dir(mbi) if not n.startswith('_')}


def _from_moo_compat():
    """The LambdaMOO compatibility shims -- tell(), pass_(), error values."""
    sys.path.insert(0, ENGINE)
    from moo import moo_compat
    return set(getattr(moo_compat, '__all__', ())) | {
        n for n in dir(moo_compat) if not n.startswith('_')}


def _from_builtins_module():
    """Everything moo.builtins exports into a verb."""
    sys.path.insert(0, ENGINE)
    from moo import builtins as mb
    return {n for n in dir(mb) if not n.startswith('_')}


# Injected by the engine but not discoverable by the scans above.
EXTRA = {
    'pobj', 'player', 'this', 'caller', 'db', 'args', 'argstr', 'argv',
    'verb', 'kwargs', 'context', 'switches',
    'dobj', 'dobjstr', 'dobjlist', 'dobj2', 'dobjlist2',
    'iobj', 'iobjstr', 'iobjlist',
    'prep', 'preplist', 'prep2', 'lhs', 'rhs', 'arglist',
    'regex_match', 'match', 'uob', 'sub', 'dob', 'iob',
    'su', 'ou', 'lu', 'cu', 'pu', 'cdu',
    'string_utils', 'object_utils', 'list_utils', 'code_utils',
    'command_utils', 'perm_utils',
    'MOOObject', 'MOOObjectRef', 'MOOError', 'ObjectFlags', 'MAX_VERB_DEPTH',
    'tick', 'remaining', 'enum', 'leader',
    # engine internals a verb may reach for
    '_effects', 'sysobj', 'Database',
    'pass_',        # built per-call by moo_compat.make_pass()
    # names arriving as call_verb keyword arguments.  These are per-call
    # rather than global, so this is the set the shipped corpus actually
    # uses -- a world adding its own will want to extend it.
    'dest', 'succ', 'osucc', 'drop', 'odrop', 'amount', 'viewer',
    'source', 'rt', 'interval', 'noun', 'enum',
}
EXTRA |= {'E_%s' % e for e in (
    'ARGS DIV FLOAT INVARG INVIND MAXREC NACC NONE PERM PROPNF QUOTA '
    'RANGE RECMOVE TYPE VARNF VERBNF').split()}


def verb_namespace_names(extra_file=None):
    """Injected names.  *extra_file* adds a world's own call_verb kwargs."""
    names = set()
    for src in (_from_namespace_builder, _from_verb_types,
                _from_builtins_module, _from_moo_compat,
                _from_moo_builtins):
        try:
            names |= src()
        except Exception as exc:                       # pragma: no cover
            print('  warning: %s failed (%s)' % (src.__name__, exc),
                  file=sys.stderr)
    names |= EXTRA
    names -= set(dir(builtins))                        # real builtins need no help
    names -= {'annotations'}
    if extra_file and os.path.exists(extra_file):
        for line in open(extra_file):
            line = line.split('#', 1)[0].strip()
            if line:
                names.add(line)
    return sorted(n for n in names if not n.startswith('__'))


RUFF = '''# Generated by tools/gen_verb_lint_config.py -- do not hand-edit.
#
# Verb code is ordinary Python, but the engine injects the verb's context
# instead of the file importing it.  Without this, a linter reports every
# injected name as undefined -- dozens per file, all false.
#
# Regenerate after upgrading MegaMOO:
#     python tools/gen_verb_lint_config.py <project-dir>

builtins = [
{names}
]
'''

STUB_HEAD = '''"""Type stubs for the MegaMOO verb namespace.

Generated by tools/gen_verb_lint_config.py -- do not hand-edit.

Point your language server at this file to get completion on the names the
engine injects into every verb.
"""
from typing import Any

'''


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    dest = argv[0] if argv else '.'

    # Into the verb tree, not the project root: ruff uses the nearest config
    # to each file, so scoping it here keeps these names from being declared
    # for a world's ordinary Python under game/, where a typo should still
    # be an error.
    for _v in ('verbs', 'moo verbs'):
        if os.path.isdir(os.path.join(dest, _v)):
            dest = os.path.join(dest, _v)
            break

    names = verb_namespace_names(os.path.join(dest, 'verb_lint_extra.txt'))
    body = '\n'.join('    "%s",' % n for n in names)
    ruff_path = os.path.join(dest, 'ruff.toml')
    with open(ruff_path, 'w') as fh:
        fh.write(RUFF.format(names=body))

    stub_path = os.path.join(dest, 'verb_context.pyi')
    with open(stub_path, 'w') as fh:
        fh.write(STUB_HEAD)
        for n in names:
            fh.write('%s: Any\n' % n)

    print('%d injected names' % len(names))
    print('wrote %s' % ruff_path)
    print('wrote %s' % stub_path)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
